project:
  type: website
  output-dir: docs

website:
  title: "The Best Pizza in New York"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - href: about.qmd
        text: Data Prep

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

