---
title: "Data Preparation"
---

### Sources

The underlying data of this report was sourced from two datasets:

1.  DAVE_PORTNOY_PIZZA_REVIEW_DATA (available here as a [.csv](https://github.com/Bravo-Lima-Delta/New-York-Pizza/blob/master/DAVE_PORTNOY_PIZZA_REVIEW_DATA.csv) – \~1.1MB)

    This data set is a pizza slice review data set from Dave Portnoy who reviews pizza locations primarily in New York. This data set includes a lot of information, but it includes the Yelp Rating of the restaurant at the time of the review, as well as Dave’s score of the pizza he ate.

2.  NYC_HEALTH_INSPECTION_DATA (available here as a [.xlsx](https://github.com/Bravo-Lima-Delta/New-York-Pizza/raw/master/NYC_HEALTH_INSPECTION_DATA.xlsx) – \~37.4MB)

    This data set provides every public health inspection result for all the restaurants in NYC.

### Data Preparation and Transformation

In order to get the data into final form for dashboard & report production, we used the joining/noodling functionality provided by Tableau Public to join/relate the two data sets together.

For expediency, we joined the two sets together using phone number as the unique identifier.

While it's possible that the combined data set could be expanded to include more establishments by means of a more thorough cleaning of the data and then by joining on other certain attributes, we felt that the 100+ pizza establishments produced by our joining methodology presents itself as a data set broad enough to build a useful product/analysis for the end-consumer.
